backend:
  name: github
  repo: hzvaan/jeonjucc # 본인의 아이디로 수정 필요
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projects"
    label: "프로젝트 게시물"
    folder: "_posts/projects"
    create: true
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "카테고리", name: "category", widget: "select", options: ["ART", "TECH", "HUMAN"]}
      - {label: "설명", name: "description", widget: "text"}
      - {label: "대표 이미지", name: "image", widget: "image"}
